// GENERATED by scripts/gen_binding.sh -- do not edit.
// Host wrappers lifted verbatim from vllm-ascend's csrc/torch_binding.cpp.
#include <torch/extension.h>
#include <torch/library.h>
#include <algorithm>
#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <torch_npu/csrc/core/npu/NPUStream.h>
#include <torch_npu/csrc/framework/OpCommand.h>
#include "torch_npu/csrc/core/npu/NPUGuard.h"
#include "acl/acl.h"
#include "ops.h"
#include "tiling/tiling_api.h"
#include "tiling/platform/platform_ascendc.h"

namespace vllm_ascend {
namespace {
constexpr int64_t ANS_GEMM_TILING_HEAD_INTS = 16;
constexpr int64_t ANS_GEMM_SINGLE_M = 128;

optiling::TCubeTiling make_ans_cube_tiling(int64_t m, int64_t n0, int64_t n_pad, int64_t k, int64_t k0)
{
    using namespace matmul_tiling;
    auto *plat = platform_ascendc::PlatformAscendCManager::GetInstance();
    TORCH_CHECK(plat != nullptr, "ans_decode_gemm: PlatformAscendCManager unavailable");
    MatmulApiTiling tiling(*plat);
    tiling.SetAType(TPosition::GM, CubeFormat::ND, matmul_tiling::DataType::DT_BF16, false);
    tiling.SetBType(TPosition::GM, CubeFormat::ND, matmul_tiling::DataType::DT_BF16, true);
    tiling.SetCType(TPosition::GM, CubeFormat::ND, matmul_tiling::DataType::DT_BF16);
    tiling.SetBias(false);
    int64_t single_m = std::min(m, ANS_GEMM_SINGLE_M);
    tiling.SetOrgShape(m, n_pad, k);
    tiling.SetShape(single_m, n0, k);
    tiling.SetBufferSpace(-1, -1, -1);
    optiling::TCubeTiling cube;
    TORCH_CHECK(tiling.GetTiling(cube) != -1,
                "ans_decode_gemm: MatmulApiTiling failed for shape ", m, "x", n_pad, "x", k, " n0=", n0);
    return cube;
}

at::Tensor pack_ans_gemm_tiling(const int32_t *head10, int32_t m_pad, int32_t sys_bytes, int32_t cube_num,
                                int32_t flag_base, const optiling::TCubeTiling &cube)
{
    int64_t nbytes = ANS_GEMM_TILING_HEAD_INTS * static_cast<int64_t>(sizeof(int32_t)) +
                     static_cast<int64_t>(sizeof(cube));
    at::Tensor pack = at::zeros({nbytes}, at::TensorOptions().dtype(at::kByte).device(at::kCPU));
    auto *bytes = static_cast<uint8_t *>(pack.data_ptr());
    auto *head = reinterpret_cast<int32_t *>(bytes);
    std::memcpy(head, head10, 10 * sizeof(int32_t));
    head[0] = m_pad;
    head[10] = sys_bytes;
    head[11] = cube_num;
    head[12] = flag_base;
    std::memcpy(bytes + ANS_GEMM_TILING_HEAD_INTS * sizeof(int32_t), &cube, sizeof(cube));
    return pack;
}

} // namespace

namespace {

constexpr int64_t ANS_FIXED_TILE_N0 = 64;
constexpr int64_t ANS_FIXED_TILE_K0 = 128;
constexpr int64_t ANS_FIXED_NSLOT = 2;

// The fused kernel's tiling head. Layout is fixed by Init() in
// csrc/kernels/ans_fixed_decode_gemm.cpp; the TCubeTiling follows it at
// ANS_GEMM_TILING_HEAD_INTS * 4 bytes.
at::Tensor pack_ans_fixed_tiling(int64_t m_pad, int64_t n_pad, int64_t k_pad, int64_t sys_bytes,
                                 int64_t cube_num, const optiling::TCubeTiling *cube, int64_t dbg = 0)
{
    int64_t nbytes = ANS_GEMM_TILING_HEAD_INTS * static_cast<int64_t>(sizeof(int32_t)) +
                     static_cast<int64_t>(sizeof(optiling::TCubeTiling));
    at::Tensor pack = at::zeros({nbytes}, at::TensorOptions().dtype(at::kByte).device(at::kCPU));
    auto *bytes = static_cast<uint8_t *>(pack.data_ptr());
    auto *head = reinterpret_cast<int32_t *>(bytes);
    head[0] = static_cast<int32_t>(m_pad);
    head[1] = static_cast<int32_t>(n_pad);
    head[2] = static_cast<int32_t>(k_pad);
    head[3] = static_cast<int32_t>(n_pad / ANS_FIXED_TILE_N0);
    head[4] = static_cast<int32_t>(k_pad / ANS_FIXED_TILE_K0);
    head[5] = static_cast<int32_t>(sys_bytes);
    head[6] = static_cast<int32_t>(cube_num);
    head[7] = 0;   // flag base; 0..3 are the only free cross-core flag ids
    head[8] = static_cast<int32_t>(dbg);   // profiling knob, 0 everywhere in production
    if (cube != nullptr) {
        std::memcpy(bytes + ANS_GEMM_TILING_HEAD_INTS * sizeof(int32_t), cube, sizeof(*cube));
    }
    return pack;
}

/* Both the Cube tiling and its device-side copy depend only on the shape, and
 * building them is not cheap: make_ans_cube_tiling runs the host tiling solver
 * and the pack has to be copied H2D. Doing that per call put ~100 us of host
 * time in front of a 151 us kernel -- more than any remaining kernel
 * optimisation is worth. A model has a handful of distinct projection shapes,
 * so a linear scan is the right structure. */
class AnsFixedTilingCache {
public:
    at::Tensor Get(int64_t m_pad, int64_t n_pad, int64_t k_pad, int64_t sys_bytes, int64_t cube_num,
                   int64_t dbg, const at::Device &device)
    {
        const int8_t dev_index = static_cast<int8_t>(device.index());
        std::lock_guard<std::mutex> guard(mu_);
        for (const Entry &e : entries_) {
            if (e.m_pad == m_pad && e.n_pad == n_pad && e.k_pad == k_pad && e.sys_bytes == sys_bytes &&
                e.cube_num == cube_num && e.dbg == dbg && e.dev_index == dev_index) {
                return e.tiling;
            }
        }
        // The tiles-only path has no Cube, so it must not run the tiling solver:
        // MatmulApiTiling rejects m == 0.
        at::Tensor tiling;
        if (m_pad > 0) {
            optiling::TCubeTiling cube =
                make_ans_cube_tiling(m_pad, ANS_FIXED_TILE_N0, n_pad, k_pad, ANS_FIXED_TILE_K0);
            tiling = pack_ans_fixed_tiling(m_pad, n_pad, k_pad, sys_bytes, cube_num, &cube, dbg).to(device);
        } else {
            tiling = pack_ans_fixed_tiling(0, n_pad, k_pad, sys_bytes, cube_num, nullptr, 0).to(device);
        }
        entries_.push_back({m_pad, n_pad, k_pad, sys_bytes, cube_num, dbg, dev_index, tiling});
        return tiling;
    }

private:
    struct Entry {
        int64_t m_pad, n_pad, k_pad, sys_bytes, cube_num, dbg;
        int8_t dev_index;
        at::Tensor tiling;
    };
    std::mutex mu_;
    std::vector<Entry> entries_;
};

AnsFixedTilingCache &ans_fixed_tiling_cache()
{
    static AnsFixedTilingCache cache;
    return cache;
}

void check_ans_fixed_planes(const at::Tensor &lplane, const at::Tensor &eplane, const at::Tensor &dplane,
                            const at::Tensor &sbase, const at::Tensor &wide_group, const at::Tensor &wide_l,
                            const at::Tensor &wide_exp, const at::Tensor &wide_tile_off, int64_t n_pad,
                            int64_t k_pad)
{
    TORCH_CHECK(n_pad > 0 && k_pad > 0 && n_pad % ANS_FIXED_TILE_N0 == 0 && k_pad % ANS_FIXED_TILE_K0 == 0,
                "ans_fixed_decode_gemm: n_pad/k_pad must be positive multiples of ", ANS_FIXED_TILE_N0, "/",
                ANS_FIXED_TILE_K0, ", got ", n_pad, "x", k_pad);
    TORCH_CHECK(lplane.is_contiguous() && eplane.is_contiguous() && dplane.is_contiguous() &&
                    sbase.is_contiguous(),
                "ans_fixed_decode_gemm: planes must be contiguous");
    TORCH_CHECK(wide_group.is_contiguous() && wide_l.is_contiguous() && wide_exp.is_contiguous() &&
                    wide_tile_off.is_contiguous(),
                "ans_fixed_decode_gemm: wide list must be contiguous");
    TORCH_CHECK(lplane.scalar_type() == at::kShort && eplane.scalar_type() == at::kShort &&
                    dplane.scalar_type() == at::kShort && sbase.scalar_type() == at::kShort,
                "ans_fixed_decode_gemm: planes must be int16 (raw uint16 bits)");
    TORCH_CHECK(wide_l.scalar_type() == at::kShort && wide_exp.scalar_type() == at::kShort,
                "ans_fixed_decode_gemm: wide_l/wide_exp must be int16");
    TORCH_CHECK(wide_group.scalar_type() == at::kInt && wide_tile_off.scalar_type() == at::kInt,
                "ans_fixed_decode_gemm: wide_group/wide_tile_off must be int32");

    const int64_t n = n_pad * k_pad;
    constexpr int64_t kGroup = 16;
    constexpr int64_t kSuper = 256;
    TORCH_CHECK(lplane.numel() == n / 2, "ans_fixed_decode_gemm: lplane must hold ", n / 2, " uint16, got ",
                lplane.numel());
    TORCH_CHECK(eplane.numel() == n / 4, "ans_fixed_decode_gemm: eplane must hold ", n / 4, ", got ",
                eplane.numel());
    TORCH_CHECK(dplane.numel() == n / (kGroup * 4), "ans_fixed_decode_gemm: dplane size mismatch");
    TORCH_CHECK(sbase.numel() == n / kSuper, "ans_fixed_decode_gemm: sbase size mismatch");
    const int64_t n_tiles = (n_pad / ANS_FIXED_TILE_N0) * (k_pad / ANS_FIXED_TILE_K0);
    TORCH_CHECK(wide_tile_off.numel() == n_tiles + 1,
                "ans_fixed_decode_gemm: wide_tile_off must hold n_tiles+1 = ", n_tiles + 1, ", got ",
                wide_tile_off.numel());
    // wide_l/wide_exp are padded to at least one group so the pointer is never
    // null when there are no wide groups; that padding must NOT be read as a
    // count -- the count comes from wide_tile_off.
    TORCH_CHECK(wide_l.numel() >= kGroup && wide_exp.numel() >= kGroup,
                "ans_fixed_decode_gemm: wide_l/wide_exp must hold at least ", kGroup, " elements");
}

}  // namespace

// Decode a gemm-tiled fixed-rate payload into a full [n_pad, k_pad] bf16
// tensor. No Cube, no cross-core flags -- this is the path used to verify the
// decode half of the fused kernel bit-exactly.
void ans_fixed_decode_tiles(at::Tensor &lplane, at::Tensor &eplane, at::Tensor &dplane, at::Tensor &sbase,
                            at::Tensor &wide_group, at::Tensor &wide_l, at::Tensor &wide_exp,
                            at::Tensor &wide_tile_off, at::Tensor &out)
{
    TORCH_CHECK(out.is_contiguous() && out.scalar_type() == at::kBFloat16,
                "ans_fixed_decode_tiles: out must be contiguous bfloat16");
    TORCH_CHECK(out.dim() == 2, "ans_fixed_decode_tiles: out must be 2D [n_pad, k_pad]");
    const int64_t n_pad = out.size(0);
    const int64_t k_pad = out.size(1);
    check_ans_fixed_planes(lplane, eplane, dplane, sbase, wide_group, wide_l, wide_exp, wide_tile_off, n_pad,
                           k_pad);

    auto *plat = platform_ascendc::PlatformAscendCManager::GetInstance();
    uint32_t cube_num = (plat != nullptr && plat->GetCoreNumAic() > 0) ? plat->GetCoreNumAic() : 20;
    // dbg -1 keys this on the no-Cube-tiling variant so it cannot collide with
    // the fused path's entry for the same shape.
    at::Tensor tiling = ans_fixed_tiling_cache().Get(0, n_pad, k_pad, 0, cube_num, -1, out.device());

    const c10_npu::OptionalNPUGuard npuGuard(out.device());
    aclrtStream stream = c10_npu::getCurrentNPUStream().stream();
    void *pl = lplane.data_ptr();
    void *pe = eplane.data_ptr();
    void *pd = dplane.data_ptr();
    void *ps = sbase.data_ptr();
    void *pwg = wide_group.data_ptr();
    void *pwl = wide_l.data_ptr();
    void *pwe = wide_exp.data_ptr();
    void *pwt = wide_tile_off.data_ptr();
    void *po = out.data_ptr();
    void *pt = tiling.data_ptr();

    at_npu::native::OpCommand cmd;
    cmd.Name("ans_fixed_decode_tiles");
    // Explicit value capture: [&] races the async OpCommand worker.
    cmd.SetCustomHandler([stream, pl, pe, pd, ps, pwg, pwl, pwe, pwt, po, pt, cube_num]() -> int {
        ans_fixed_decode_tiles_impl(stream, pl, pe, pd, ps, pwg, pwl, pwe, pwt, po, pt, cube_num);
        return 0;
    });
    cmd.Run();
}

// y = x @ W^T with W arriving as a fixed-rate payload, decoded on the AIV into
// a workspace panel that the Cube consumes.
//
// Correct, and slower than streaming bf16 -- see the header comment in the
// kernel. This exists for weight capacity, not for speed.
at::Tensor ans_fixed_decode_gemm(at::Tensor &x, at::Tensor &lplane, at::Tensor &eplane, at::Tensor &dplane,
                                 at::Tensor &sbase, at::Tensor &wide_group, at::Tensor &wide_l,
                                 at::Tensor &wide_exp, at::Tensor &wide_tile_off, int64_t n_pad,
                                 int64_t k_pad, int64_t dbg)
{
    TORCH_CHECK(x.dim() == 2 && x.is_contiguous() && x.scalar_type() == at::kBFloat16,
                "ans_fixed_decode_gemm: x must be 2D contiguous bfloat16");
    TORCH_CHECK(x.size(1) == k_pad, "ans_fixed_decode_gemm: x must be [M, ", k_pad, "], got k=", x.size(1));
    check_ans_fixed_planes(lplane, eplane, dplane, sbase, wide_group, wide_l, wide_exp, wide_tile_off, n_pad,
                           k_pad);

    const int64_t m = x.size(0);
    const int64_t m_pad = (m + 15) / 16 * 16;
    at::Tensor x_work = x;
    if (m_pad != m) {
        // at::empty, not at::zeros. Rows m..m_pad-1 are never read: in a GEMM
        // output row r depends only on A row r, and those rows are narrowed
        // off below. Zeroing them is a whole extra kernel launch, and at M = 1
        // -- every decode step -- it measured ~0.09 ms per linear.
        x_work = at::empty({m_pad, k_pad}, x.options());
        x_work.narrow(0, 0, m).copy_(x);
    }
    at::Tensor y = at::empty({m_pad, n_pad}, x.options());

    auto *plat = platform_ascendc::PlatformAscendCManager::GetInstance();
    uint32_t cube_num = (plat != nullptr && plat->GetCoreNumAic() > 0) ? plat->GetCoreNumAic() : 20;
    int64_t sys_ws = (plat != nullptr) ? static_cast<int64_t>(plat->GetLibApiWorkSpaceSize()) : 0;
    sys_ws = std::max<int64_t>(sys_ws, 16 * 1024 * 1024);
    sys_ws = (sys_ws + 511) / 512 * 512;
    TORCH_CHECK(sys_ws <= INT32_MAX, "ans_fixed_decode_gemm: sys workspace too large");

    at::Tensor tiling =
        ans_fixed_tiling_cache().Get(m_pad, n_pad, k_pad, sys_ws, cube_num, dbg, x.device());

    // ANS_FIXED_NSLOT panels per cube block, rotated against the Cube. Must
    // match NSLOT in csrc/kernels/ans_fixed_decode_gemm.cpp.
    int64_t user_ws = static_cast<int64_t>(cube_num) * ANS_FIXED_NSLOT * ANS_FIXED_TILE_N0 * k_pad *
                      static_cast<int64_t>(sizeof(uint16_t));
    // at::empty, not at::zeros: the kernel writes every panel byte before the
    // Cube reads it, and zeroing 40+ MB per call costs more than the GEMM.
    at::Tensor ws = at::empty({sys_ws + user_ws}, x.options().dtype(at::kByte));

    const c10_npu::OptionalNPUGuard npuGuard(x.device());
    aclrtStream stream = c10_npu::getCurrentNPUStream().stream();
    void *px = x_work.data_ptr();
    void *pl = lplane.data_ptr();
    void *pe = eplane.data_ptr();
    void *pd = dplane.data_ptr();
    void *ps = sbase.data_ptr();
    void *pwg = wide_group.data_ptr();
    void *pwl = wide_l.data_ptr();
    void *pwe = wide_exp.data_ptr();
    void *pwt = wide_tile_off.data_ptr();
    void *py = y.data_ptr();
    void *pws = ws.data_ptr();
    void *pt = tiling.data_ptr();

    at_npu::native::OpCommand cmd;
    cmd.Name("ans_fixed_decode_gemm");
    cmd.SetCustomHandler(
        [stream, px, pl, pe, pd, ps, pwg, pwl, pwe, pwt, py, pws, pt, cube_num]() -> int {
            ans_fixed_decode_gemm_impl(stream, px, pl, pe, pd, ps, pwg, pwl, pwe, pwt, py, pws, pt,
                                       cube_num);
            return 0;
        });
    cmd.Run();
    return (m_pad != m) ? y.narrow(0, 0, m).contiguous() : y;
}

}  // namespace vllm_ascend

TORCH_LIBRARY_FRAGMENT(rans, m) {
    m.def("ans_fixed_decode_tiles(Tensor lplane, Tensor eplane, Tensor dplane, Tensor sbase, "
          "Tensor wide_group, Tensor wide_l, Tensor wide_exp, Tensor wide_tile_off, Tensor! out) -> ()");
    m.def("ans_fixed_decode_gemm(Tensor x, Tensor lplane, Tensor eplane, Tensor dplane, Tensor sbase, "
          "Tensor wide_group, Tensor wide_l, Tensor wide_exp, Tensor wide_tile_off, int n_pad, int k_pad, "
          "int dbg=0) -> Tensor");
}
TORCH_LIBRARY_IMPL(rans, PrivateUse1, m) {
    m.impl("ans_fixed_decode_tiles", TORCH_FN(vllm_ascend::ans_fixed_decode_tiles));
    m.impl("ans_fixed_decode_gemm", TORCH_FN(vllm_ascend::ans_fixed_decode_gemm));
}
