#!/bin/bash
# Emit the torch binding by lifting the host wrappers out of the vllm-ascend
# checkout VERBATIM by line span, so this can never test a stale copy. $1 = out.
set -e
AWORK="${AWORK:-/home/gongcheng/PureInt8LLMPretraining/awork}"
SRC="$AWORK/csrc/torch_binding.cpp"
[ -f "$SRC" ] || { echo "gen_binding: $SRC not found (set AWORK=)"; exit 1; }
START=$(grep -n "^constexpr int64_t ANS_GEMM_TILING_HEAD_INTS" "$SRC" | cut -d: -f1)
END=$(grep -n "^void ans_decode_gemm(at::Tensor &x, at::Tensor &payload" "$SRC" | cut -d: -f1)
[ -n "$START" ] && [ -n "$END" ] || { echo "gen_binding: span markers not found"; exit 1; }
{
  cat <<'HDR'
// GENERATED by scripts/gen_binding.sh -- do not edit.
// Host wrappers lifted verbatim from vllm-ascend's csrc/torch_binding.cpp.
#include <torch/extension.h>
#include <torch/library.h>
#include <algorithm>
#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <torch_npu/csrc/core/npu/NPUStream.h>
#include <torch_npu/csrc/framework/OpCommand.h>
#include "torch_npu/csrc/core/npu/NPUGuard.h"
#include "acl/acl.h"
#include "ops.h"
#include "tiling/tiling_api.h"
#include "tiling/platform/platform_ascendc.h"

namespace vllm_ascend {
namespace {
HDR
  sed -n "${START},$((END-1))p" "$SRC"
  cat <<'FTR'
}  // namespace vllm_ascend

TORCH_LIBRARY_FRAGMENT(rans, m) {
    m.def("ans_fixed_decode_tiles(Tensor lplane, Tensor eplane, Tensor dplane, Tensor sbase, "
          "Tensor wide_group, Tensor wide_l, Tensor wide_exp, Tensor wide_tile_off, Tensor! out) -> ()");
    m.def("ans_fixed_decode_gemm(Tensor x, Tensor lplane, Tensor eplane, Tensor dplane, Tensor sbase, "
          "Tensor wide_group, Tensor wide_l, Tensor wide_exp, Tensor wide_tile_off, int n_pad, int k_pad, "
          "int dbg=0) -> Tensor");
}
TORCH_LIBRARY_IMPL(rans, PrivateUse1, m) {
    m.impl("ans_fixed_decode_tiles", TORCH_FN(vllm_ascend::ans_fixed_decode_tiles));
    m.impl("ans_fixed_decode_gemm", TORCH_FN(vllm_ascend::ans_fixed_decode_gemm));
}
FTR
} > "$1"
